<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE yml_catalog [
        <!ELEMENT yml_catalog (shop)*>
        <!ATTLIST yml_catalog
                date CDATA #REQUIRED>
        <!ELEMENT shop (name|company|url|phone|platform|version|currencies|categories|offers)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT company (#PCDATA)>
        <!ELEMENT url (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ELEMENT platform (#PCDATA)>
        <!ELEMENT version (#PCDATA)>
        <!ELEMENT currencies (currency)*>
        <!ELEMENT currency (#PCDATA)>
        <!ATTLIST currency
                id CDATA #REQUIRED
                rate CDATA #REQUIRED>
        <!ELEMENT categories (category)*>
        <!ELEMENT category (#PCDATA)>
        <!ATTLIST category
                id CDATA #REQUIRED
                parentId CDATA #IMPLIED>
        <!ELEMENT offers (offer)*>
        <!ELEMENT offer (url|price|currencyId|categoryId|picture|delivery|quantity_in_stock|name|vendor|param|weight)*>
        <!ATTLIST offer
                available CDATA #REQUIRED
                group_id CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT currencyId (#PCDATA)>
        <!ELEMENT categoryId (#PCDATA)>
        <!ELEMENT picture (#PCDATA)>
        <!ELEMENT delivery (#PCDATA)>
        <!ELEMENT quantity_in_stock (#PCDATA)>
        <!ELEMENT vendor (#PCDATA)>
        <!ELEMENT param (#PCDATA)>
        <!ATTLIST param
                name CDATA #REQUIRED>
        <!ELEMENT weight (#PCDATA)>
        ]>
<yml_catalog date="2021-01-29 12:38">
<shop>
<name>Интернет-магазин ALTEK</name>
<company>Интернет-магазин ALTEK</company>
<url>https://altek.ua/</url>
<phone>+38 067 711 71 71</phone>
<platform>Yandex.YML for OpenCart (ocStore)</platform>
<version>1.9.3</version>
<currencies>
<currency id="USD" rate="28"/>
<currency id="UAH" rate="1"/>
<currency id="EUR" rate="68.0272"/>
</currencies>
<categories>
<category id="4348832" >
Теплові насоси</category>
<category id="5198241" >
Сонячні електростанції</category>
<category id="3967155" >
Геліосистеми</category>
<category id="84052066" parentId="3955071" >
Гібридні інвертори</category>
<category id="84011040" >
Мобільні сонячні зарядки</category>
<category id="4335715" parentId="3967155" >
Запасні частини для геліосистем</category>
<category id="4260130" parentId="3967155" >
Контролери для геліосистем</category>
<category id="4333491" parentId="3967155" >
Баки для нагріву води</category>
<category id="4310324" parentId="3967155" >
Сезонні геліосистеми</category>
<category id="84011142" parentId="3967155" >
Повітряні колектори</category>
<category id="4332084" parentId="3967155" >
Всесезонні геліосистеми</category>
<category id="4333587" parentId="3967155" >
Насосні станції і насоси</category>
<category id="84011150" parentId="3967155" >
Розширювальні баки</category>
<category id="3955056" parentId="5198241" >
Акумуляторні батареї</category>
<category id="3955051" parentId="5198241" >
Фотомодулі сонячні батареї</category>
<category id="3955054" parentId="5198241" >
Контролери заряду АКБ</category>
<category id="84011032" parentId="5198241" >
Монтажні матеріали для СЕС</category>
<category id="84011028" parentId="5198241" >
Сонячна черепиця</category>
<category id="3955071" parentId="5198241" >
Інвертори</category>
<category id="84052062" parentId="3955071" >
Мережеві інвертори</category>
<category id="84052061" parentId="3955071" >
Автономні інвертори</category>
<category id="84052067" parentId="5198241" >
Захист та лічильники</category>
</categories>
<offers>
<offer id="2111138" group_id="1557" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abd-b-0200-s-dvumya-teploobmennikami</url>
<price>504.00</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/catalog/products/baki/2111138/2111138_2.jpg</picture>
<picture>https://altek.ua/image/catalog/products/baki/2111138/2111138_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABD-B-0200 с двумя теплообменниками</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2111140" group_id="1558" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abd-0500-s-dvumya-teploobmennikami</url>
<price>985.50</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/catalog/products/baki/2111140/2111140_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/baki/2111140/2111140_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABD-0500 с двумя теплообменниками</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2111141" group_id="1559" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abd-0800-s-dvumya-teploobmennikami</url>
<price>1620.00</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/catalog/products/baki/2112835/2112835_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABD-0800 с двумя теплообменниками</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2111143" group_id="1560" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abd-1000-s-dvumya-teploobmennikami</url>
<price>1791.00</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/cache/catalog/products/baki/2111143/2111143-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABD-1000 с двумя теплообменниками</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2111144" group_id="1561" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abd-b-0300-s-dvumya-teploobmennikami</url>
<price>693.00</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/catalog/products/baki/2111144/2111144_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/baki/2111144/2111144_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABD-B-0300 с двумя теплообменниками</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2111137" group_id="1562" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abs-b-0200-01-s-odnim-teploobmennikom</url>
<price>460.80</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/catalog/products/baki/2111138/2111138_2.jpg</picture>
<picture>https://altek.ua/image/catalog/products/baki/2111138/2111138_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABS-B-0200-01 с одним теплообменником</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2111139" group_id="1563" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abs-b-0300-01-s-odnim-teploobmennikom</url>
<price>648.00</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/catalog/products/baki/2111144/2111144_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/baki/2111144/2111144_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABS-B-0300-01 с одним теплообменником</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2111142" group_id="1564" available="true" >
<url>https://altek.ua/ua/geliosistemy/baki-dlya-nagreva-vody/vodonagrevatel-altek-abs-1000-s-odnim-teploobmennikom</url>
<price>1683.00</price>
<currencyId>USD</currencyId>
<categoryId>4333491</categoryId>
<picture>https://altek.ua/image/catalog/products/baki/2111142/2111142_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/baki/2111142/2111142_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Водонагреватель ALTEK ABS-1000 с одним теплообменником</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2110803" group_id="1565" available="true" >
<url>https://altek.ua/ua/geliosistemy/vozdushnye-kollektory/solnechnyj-kollektor-altek-alt-ah-1000-vozdushnyj</url>
<price>288.00</price>
<currencyId>USD</currencyId>
<categoryId>84011142</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/2110803/2110803_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/2110803/2110803_3.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/2110803/2110803_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный воздушный коллектор ALTEK ALT-AH-1000</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2110804" group_id="1566" available="true" >
<url>https://altek.ua/ua/geliosistemy/vozdushnye-kollektory/solnechnyj-kollektor-altek-alt-ah-2000-vozdushnyj</url>
<price>567.00</price>
<currencyId>USD</currencyId>
<categoryId>84011142</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/2110803/2110803_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/2110803/2110803_3.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/2110803/2110803_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор ALTEK ALT-AH-2000 воздушный</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="98843" group_id="1567" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-bez-zadnih-opor-altek-sc-lh1-30-vakuumnyj</url>
<price>677.70</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/98843/98843_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор без задних опор ALTEK SC-LH1-30 вакуумный</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">30</param>
<param name="Серія">SC-LH1</param>
</offer>
<offer id="100382" group_id="1568" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-bez-zadnih-opor-altek-sc-lh2-20-vakuumnyj</url>
<price>494.10</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/100382/100382_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор без задних опор ALTEK SC-LH2-20 вакуумный</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">20</param>
<param name="Серія">SC-LH2</param>
</offer>
<offer id="101798" group_id="1569" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-bez-zadnih-opor-altek-sc-lh2-30-balkonnogo-tipa</url>
<price>592.20</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/101798/101798_3.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/101798/101798.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/101798/101798_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор без задних опор ALTEK SC-LH2-30 балконного типа</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">30</param>
<param name="Серія">SC-LH2</param>
</offer>
<offer id="101797" group_id="1570" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-bez-zadnih-opor-altek-sc-lh3-20</url>
<price>551.70</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/101797/101797_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор без задних опор ALTEK SC-LH3-20</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">20</param>
<param name="Серія">SC-LH3</param>
</offer>
<offer id="98845" group_id="1571" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-bez-zadnih-opor-altek-sc-lh3-30</url>
<price>818.10</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/98843/98843_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор без задних опор ALTEK SC-LH3-30</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">30</param>
<param name="Серія">SC-LH3</param>
</offer>
<offer id="102610" group_id="1572" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/%D1%81%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80-sunrain-tz58-1800-10r1a-%D0%B2%D0%B0%D0%BA%D1%83%D1%83%D0%BC%D0%BD%D1%8B%D0%B9</url>
<price>355.50</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор Sunrain TZ58/1800-10R1A вакуумный</name>
<vendor>SUNRAIN</vendor>
<param name="Количество трубок, шт">10</param>
<param name="Серія">TZ-R1A</param>
</offer>
<offer id="102604" group_id="1573" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/%D1%81%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80-sunrain-tz58-1800-30r1a-%D0%B2%D0%B0%D0%BA%D1%83%D1%83%D0%BC%D0%BD%D1%8B%D0%B9</url>
<price>944.10</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор Sunrain TZ58/1800-30R1A вакуумный</name>
<vendor>SUNRAIN</vendor>
<param name="Количество трубок, шт">30</param>
<param name="Серія">TZ-R1A</param>
</offer>
<offer id="93342" group_id="1574" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/%D1%81%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80-altek-sc-lh2-10-%D0%B2%D0%B0%D0%BA%D1%83%D1%83%D0%BC%D0%BD%D1%8B%D0%B9</url>
<price>306.90</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/93342/solnechnyj-kollektor-altek-sc-lh2-10-vakuumnyj.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/93342/93342_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор ALTEK SC-LH2-10 вакуумный</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">10</param>
<param name="Серія">SC-LH2</param>
</offer>
<offer id="98844" group_id="1575" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-bez-zadnih-opor-altek-sc-lh2-30-vakuumnyj</url>
<price>750.60</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/98844/98844_2.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/98844/98844_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/98844/98844_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор без задних опор ALTEK SC-LH2-30 вакуумный</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">30</param>
<param name="Серія">SC-LH2</param>
</offer>
<offer id="2110787" group_id="1576" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/%D1%81%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80-altek-premium-line-tz58-1800-20r1a</url>
<price>646.20</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор Altek Premium Line TZ58/1800-20R1A</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">20</param>
<param name="Серія">TZ-R1A</param>
</offer>
<offer id="2111356" group_id="1577" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-bez-opory-altek-premium-line-tz58-1800-30r1a-bez-opory</url>
<price>908.10</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор без опоры Altek Premium Line TZ58/1800-30R1A  без опоры</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">30</param>
<param name="Серія">TZ-R1A</param>
<param name="Комплектація">Без опори</param>
</offer>
<offer id="92058" group_id="1578" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/%D1%81%D0%BE%D0%BB%D0%BD%D0%B5%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80-altek-sc-lh2-15-%D0%B2%D0%B0%D0%BA%D1%83%D1%83%D0%BC%D0%BD%D1%8B%D0%B9</url>
<price>408.60</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/92058/92058_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/92058/92058_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор ALTEK SC-LH2-15 вакуумный</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">15</param>
<param name="Серія">SC-LH2</param>
</offer>
<offer id="109548" group_id="1579" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-s-zadnimi-oporami-altek-sc-lh2-5</url>
<price>127.80</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109548/solnechnyj-kollektor-s-zadnimi-oporami-altek-sc-lh2-5.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109548/109548__2.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109548/109548__3.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109548/109548__4.jpg</picture>
<picture>https://altek.ua/image/cache/catalog/products/geliosistemy/109548/109548__6-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор с задними опорами ALTEK SC-LH2-5</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">5</param>
<param name="Серія">SC-LH2</param>
</offer>
<offer id="109550" group_id="1580" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-s-zadnimi-oporami-altek-sc-lh3-5</url>
<price>127.80</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109550/109550_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109550/109550_2.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109550/109550_5.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109550/109550_3.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109550/109550_4.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор с задними опорами ALTEK SC-LH3-5</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">5</param>
<param name="Серія">SC-LH3</param>
</offer>
<offer id="109822" group_id="1581" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-v-komplekte-s-oporoj-altek-sc-hd-20-drainback</url>
<price>567.00</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109822/109822_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109822/109822_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор в комплекте с опорой ALTEK SC-HD-20 (Drainback)</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">20</param>
<param name="Серія">SC-HD</param>
</offer>
<offer id="109823" group_id="1582" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-v-komplekte-s-oporoj-altek-sc-hd-30-drainback</url>
<price>850.50</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109822/109822_1.jpg</picture>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109822/109822_2.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор в комплекте с опорой ALTEK SC-HD-30 (Drainback)</name>
<vendor>ALTEK</vendor>
<param name="Количество трубок, шт">30</param>
<param name="Серія">SC-HD</param>
</offer>
<offer id="109625" group_id="1584" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-hewalex-ks2100-tlp-ac-ploskij</url>
<price>372.18</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109625/109625.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор HEWALEX KS2100 TLP AC плоский</name>
<vendor>HEWALEX</vendor>
<param name="Виробник">HEWALEX</param>
<param name="Країна">Польща</param>
<param name="Серія">KS</param>
</offer>
<offer id="2111460" group_id="1585" available="true" >
<url>https://altek.ua/ua/geliosistemy/vsesezonnye-geliosistemy/solnechnyj-kollektor-hewalex-ks2100f-tlp-ac-ploskij</url>
<price>391.89</price>
<currencyId>USD</currencyId>
<categoryId>4332084</categoryId>
<picture>https://altek.ua/image/catalog/products/geliosistemy/109625/109625.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Солнечный коллектор HEWALEX KS2100F TLP AC плоский</name>
<vendor>HEWALEX</vendor>
<param name="Серія">KS</param>
</offer>
<offer id="101387" group_id="1586" available="true" >
<url>https://altek.ua/ua/geliosistemy/nasosnye-stancii-i-nasosy/avtomaticheskij-vozduhootvodchik-novasfer-3-8nr</url>
<price>18.40</price>
<currencyId>USD</currencyId>
<categoryId>4333587</categoryId>
<picture>https://altek.ua/image/catalog/products/nasosni%20grupy/101387/101387_1.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Автоматический воздухоотводчик Novasfer 3/8&quot;НР</name>
<vendor>NOVASFER</vendor>
</offer>
<offer id="2110848" group_id="1587" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/dvojnaya-gofrirovannaya-truba-2-x-16-buhta-10-m-altek-dn20-izolyaciya-13-mm</url>
<price>27.43</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/catalog/products/montag/106057%2C106060%2C106058%2C106061%2C106059%2C106062/106057%2C106060%2C106058%2C106061%2C106059%2C106062.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Двойная гофрированная труба 2 X 16, бухта 10 м ALTEK DN20, изоляция 13 мм</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="106057" group_id="1588" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/dvojnaya-gofrirovannaya-truba-2-x-16-buhta-15-m-altek-dn16-izolyaciya-13-mm</url>
<price>1.00</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/catalog/products/montag/106057%2C106060%2C106058%2C106061%2C106059%2C106062/106057%2C106060%2C106058%2C106061%2C106059%2C106062.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>0</quantity_in_stock>
<name>Двойная гофрированная труба 2 X 16, бухта 15 м ALTEK DN16, изоляция 13 мм</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="2110847" group_id="1589" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/dvojnaya-gofrirovannaya-truba-2-x-16-buhta-10-m-altek-dn16-izolyaciya-13-mm</url>
<price>22.54</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/catalog/products/montag/106057%2C106060%2C106058%2C106061%2C106059%2C106062/106057%2C106060%2C106058%2C106061%2C106059%2C106062.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Двойная гофрированная труба 2 X 16, бухта 10 м ALTEK DN16, изоляция 13 мм</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="106060" group_id="1590" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/dvojnaya-gofrirovannaya-truba-2-x-16-buhta-25-m-altek-dn16-izolyaciya-13-mm</url>
<price>1.00</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/catalog/products/montag/106057%2C106060%2C106058%2C106061%2C106059%2C106062/106057%2C106060%2C106058%2C106061%2C106059%2C106062.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>0</quantity_in_stock>
<name>Двойная гофрированная труба 2 X 16, бухта 25 м ALTEK DN16, изоляция 13 мм</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="106058" group_id="1591" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/dvojnaya-gofrirovannaya-truba-2-x-16-buhta-15-m-altek-dn20-izolyaciya-13-mm</url>
<price>1.00</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/catalog/products/montag/106057%2C106060%2C106058%2C106061%2C106059%2C106062/106057%2C106060%2C106058%2C106061%2C106059%2C106062.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>0</quantity_in_stock>
<name>Двойная гофрированная труба 2 X 16, бухта 15 м ALTEK DN20, изоляция 13 мм.</name>
<vendor>ALTEK</vendor>
</offer>
<offer id="94100" group_id="1592" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/bak-vodyanoj-sistem-sd-t2-10-altek-100-l</url>
<price>151.20</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/cache/catalog/products/teplo/94100/94100-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Бак водяной систем SD-T2-10 ALTEK 100 л</name>
<vendor>ALTEK</vendor>
<param name="Елемент">Бак</param>
<param name="Объем, л">100</param>
</offer>
<offer id="94102" group_id="1593" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/bak-vodyanoj-dlya-sistem-sd-t2-15-altek-150-l</url>
<price>171.90</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/cache/catalog/products/teplo/94102/94102-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Бак водяной для систем SD-T2-15 ALTEK 150 л</name>
<vendor>ALTEK</vendor>
<param name="Елемент">Бак</param>
<param name="Объем, л">150</param>
</offer>
<offer id="107957" group_id="1594" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/bak-vodyanoj-dlya-sistem-sd-t2l-15-altek-150-l</url>
<price>189.90</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/cache/catalog/products/teplo/94102/94102-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Бак водяной для систем SD-T2L-15 ALTEK 150 л</name>
<vendor>ALTEK</vendor>
<param name="Елемент">Бак</param>
<param name="Объем, л">150</param>
</offer>
<offer id="94589" group_id="1595" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/bak-vodyanoj-dlya-sistem-sp-s-15-altek-150-l</url>
<price>369.90</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/cache/catalog/products/teplo/2112750/2112750-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Бак водяной для систем SP-С-15 ALTEK 150 л</name>
<vendor>ALTEK</vendor>
<param name="Елемент">Бак</param>
<param name="Объем, л">150</param>
</offer>
<offer id="107962" group_id="1596" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/bak-vodyanoj-dlya-sistem-sp-cl-20-altek-200-l</url>
<price>498.60</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/cache/catalog/products/teplo/107962/107962-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Бак водяной для систем SP-CL-20 ALTEK 200 л</name>
<vendor>ALTEK</vendor>
<param name="Елемент">Бак</param>
<param name="Объем, л">200</param>
</offer>
<offer id="99465" group_id="1597" available="true" >
<url>https://altek.ua/ua/geliosistemy/zapasnye-chasti-dlya-geliosistem/bak-vodyanoj-dlya-sistem-sp-h1-20-altek-200-l</url>
<price>547.20</price>
<currencyId>USD</currencyId>
<categoryId>4335715</categoryId>
<picture>https://altek.ua/image/cache/catalog/products/teplo/95308/95308-600x600.jpg</picture>
<delivery>true</delivery>
<quantity_in_stock>999</quantity_in_stock>
<name>Бак водяной для систем SP-H1-20 ALTEK 200 л</name>
<vendor>ALTEK</vendor>
<param name="Елемент">Бак</param>
<param name="Объем, л">200</param>
</offer>
<offer id="94590" group_id="1598" available="true" >